### PR TITLE
chore: add vue and express boilerplate

### LINKED ISSUE #2: create a boilerplate
push a boilerplate with some basic Vue and Express setup

### PR DESCRIPTION
**Pull request by AntonTymczenko**
closes #2

### CODE REVIEW

**Comment by AntonTymczenko** [comment]
if you have any suggestions on folder structure and stuff like that – it's better to say it now, when we're only starting :smile:

**Review by tomski80 — COMMENTED** [review]
I don't know enough Vue to comment on structure too much. The only thing that catch my eye is file name in /src/router/ being index.js - I would think it would be better to name it router.js unless index.js is a standard Vue naming convention ?  I will let Svetlana approve it as I don't have experience with this frameworks.

**Comment by AntonTymczenko** [comment]
It is a standard vue's  boilerplate. And when you name files 'index.js' then you can call them just by naming their folder. So then in other file you'll call it not `router/router.js` or `router/index.js` but just `router`

**Review by svmi3195 — APPROVED** [review]
I think it's ok. As I understand it follows this structure http://vuejs-templates.github.io/webpack/structure.html which is kind of standard, and we don't invent anything new and dangerous here.
As for naming router file, as far as I've seen it's quite common to name folder "router" and the file just "index.js"

**Comment by tomski80** [comment]
OK then, if it's standard structure then we should keep it that way :). thanks.

**Pull request merged**
