### PR TITLE
feat: adds vuex store and one new collection closes #14

### LINKED ISSUE #14: write predefined collection
about 10 cards would be enough
use $store (Vuex)

connected to #38

### PR DESCRIPTION
**Pull request by tomski80**
adds vuex store and one new collection, moves collection from lesson to store, temporarily updates Lesson component to use data from store but this needs updating later.

### CODE REVIEW

**Comment by tomski80** [comment]
That what I came up with considering my limited Vuex understanding. Please have a look at it and if it is not the right way then I will change it. I have updated Lesson component mainly so I can see if it is actually working, so it will need to be restructure later on.

**Comment by svmi3195** [comment]
>  {q: 'Spain', a: 'Madrit'}

Ain't it Madrid in English?

**Comment by AntonTymczenko** [comment]
so it needs some fixes in the collection:
 
> {q: 'Ukraine', a: 'Kyiv'}
> {q: 'Spain', a: 'Madrid'}
> {q: 'Northern Ireland', a: 'Belfast'},

and indentation should be 2 spaces.

**Review by AntonTymczenko — APPROVED** [review]
I would change indentation in a `collections` object, but we'll get rid of it later, anyway

**Review by svmi3195 — APPROVED** [review]
I think it's ok now.

**Pull request merged**
