### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by AntonTymczenko**
Oh, it is huge. But be patient. Most of all it's just moving from one file to another.

### CODE REVIEW

**Review by svmi3195 — APPROVED** [review]
It looks good to me. As far as I tested I only found that bug with making empty collection if leave page (and solving this depends on how we approach saving functionality in general).
It seems a bit like overkill to me making a variable for `this.id` just to use it once afterwards (like in remove or checkLastCard methods), but that's matter of stylistic preferences :)

**Comment by AntonTymczenko** [comment]
@svmi3195 could you please specify in code those places which you consider overkilling? I'll review them

**Comment by svmi3195** [comment]
I meant, why avoid using `this.id`, it's not much longer than `id`.

**Comment by AntonTymczenko** [comment]
```
const id = this.id
this.$store.commit('removeCard', { id, index })
```
In this place? It just allows to pass a neat object with ES6 syntax :grin: `{ id, index }` instead of `{ id: this.id, index }` The second expression kinda breaks all the consistency in arguments of `commit` method. If it would be only one argument, as later in another file... ` this.$store.commit('removeCollection', this.id)` <– this time I just passed `this.id` and not even as an object, it's ok.

**Review by tomski80 — APPROVED** [review]
It looks good to me.

**Pull request merged**
