### PR TITLE
docs: Add contribution guidelines

### LINKED ISSUE #26: docs: write contribution guidelines
Style guide on naming branches,  writing commit messages and general code style.

### PR DESCRIPTION
**Pull request by AntonTymczenko**
closes #26

### CODE REVIEW

**Comment by svmi3195** [comment]
I think font for "Naming Git branches" should be bigger since it's section's title. Make it like font size in "General", "Vue" and other sections. Or, if it's a sub-section of "Git workflow" change it's position it content's list in the beginning.

**Comment by svmi3195** [comment]
Maybe instead of "Indentation consists of two spaces." write something like "The unit of indentation is two spaces." It's just language thing, of course.

**Comment by svmi3195** [comment]
"When in a scope of a particular sprint there is a feature, around which several user stories could be gathered, these stories create an issue with a title in format feat: few words of description. And the stories go into description block of this issue."
Umm, English is not my native language, but maybe we can tweak wording somehow?
"When there is a feature in a scope of a particular sprint which fulfills of several user stories, these stories create an issue with a title in format `feat: few words of description`. And the stories are listed in the description block of the issue."
I am not sure if this is better, just a suggestion.

**Comment by svmi3195** [comment]
"All tasks which are related to mentioned in a previous paragraph stories"
I think words order should be a bit different
"All tasks related to stories mentioned in a previous paragraph"

**Review by svmi3195 — APPROVED** [review]
I commented on all things I could think of and I think it's good - if we find more ways to improve docs, we will :)

**Review by tomski80 — COMMENTED** [review]
I have few improvements to grammar structure, but they are not critical and maybe little subjective. It looks good to me overall. 

So we could not predict how shiny would be our application at the end of Chingu's Voyage-4.

I think it would be better : 

So we could not predict how shiny our application would be at the end of Chingu's Voyage-4.

By opening an issue one can request some enhancement in UI/UX or report about some bugs

maybe better: 

By opening an issue one can request some enhancement in UI/UX or report a bug.

So despite negative semantics of a word "issue", it is both about good and bad sides of user's experience.

maybe better: 

So despite negative semantics of a word "issue", it can be used as a tool to improve users experience.

**Review by tomski80 — APPROVED** [review]
I meant to approve it before not just comment.

**Pull request merged**
