### PR TITLE
Disallow making empty card with whitespaces

### LINKED ISSUE #80: User can make an empty card with whitespaces
I can make a card with whitespaces in q and a - it will look empty

### PR DESCRIPTION
**Pull request by svmi3195**
Looks like using vue's `trim` modifier on input takes care of https://github.com/chingu-voyage4/Bears-Team-15/issues/80

closes #80

### CODE REVIEW

**Review by tomski80 — COMMENTED** [review]
Are you sure this works, it seems not doing anything for me.

**Review by AntonTymczenko — CHANGES_REQUESTED** [review]
works good in both browsers for card properties, but the collection name should be trimmed too

**Comment by svmi3195** [comment]
Will add trim for collection too when I get to my laptop.

**Review by AntonTymczenko — APPROVED** [review]

**Comment by AntonTymczenko** [comment]
I think you'll have to merge `development` to this branch and push it again

**Pull request merged**
